/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.AgendamentoExamesDAO;
import dao.ConsultasDAO;
import dao.FormaPagamentoDAO;
import dao.FuncionarioDAO;
import dao.PacienteDAO;
import dao.PlanoDAO;
import dao.ProntuarioDAO;
import gema.Formatacao;
import gema.Gema;
import gema.JSON;
import gema.Mensagens;
import gema.ValidaCampo;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.Consultas;
import negocio.Funcionario;
import negocio.Paciente;
import negocio.Plano;
import negocio.Usuario;
import org.hibernate.HibernateException;
import persistencia.BasicScreen;
import registros.Atividade;
import registros.PermissaoG;

/**
 *
 * @author Lucas
 */
public class AgendamentoConsultaJIF extends javax.swing.JInternalFrame implements BasicScreen {
    
    Paciente paciente;
    Funcionario funcionario;
    Consultas consultas;
    Plano plano;
    Usuario usuario;
    TreeMap<Integer, Boolean> can;

    /**
     * Creates new form AgendamentoConsulta
     */
    public AgendamentoConsultaJIF(Usuario usuario, TreeMap<Integer, Boolean> can) {
        initComponents();
        limpar();
        //btnDeletar.setVisible(false);
        this.usuario = usuario;
        this.can = can;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfdProfissional = new javax.swing.JTextField();
        btnPesquisar1 = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        tfdPlano = new javax.swing.JTextField();
        btnPesquisar2 = new javax.swing.JToggleButton();
        tfdPaciente = new javax.swing.JTextField();
        tfData = new javax.swing.JFormattedTextField();
        comboHora = new javax.swing.JComboBox<>();
        btnHora = new javax.swing.JButton();
        jp_botoesAcao = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JToggleButton();
        btnPesquisar3 = new javax.swing.JToggleButton();
        btnDeletar = new javax.swing.JToggleButton();
        btnEditar = new javax.swing.JToggleButton();
        btnSalvar = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setTitle("Agendamento de consultas");
        setName("Agendamento de consultas"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agendamento de consulta");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da consulta"));

        jLabel10.setText("Hora (*)");

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel9.setText("Data (*)");

        jLabel3.setText("Paciente (*)");

        jLabel4.setText("Profissional (*)");

        tfdProfissional.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfdProfissional.setText("Urologista do Caye");
        tfdProfissional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfdProfissionalActionPerformed(evt);
            }
        });

        btnPesquisar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier.png"))); // NOI18N
        btnPesquisar1.setText("Pesquisar");
        btnPesquisar1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Plano Saúde (*)");

        tfdPlano.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdPlanoFocusLost(evt);
            }
        });

        btnPesquisar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier.png"))); // NOI18N
        btnPesquisar2.setText("Pesquisar");
        btnPesquisar2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPesquisar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar2ActionPerformed(evt);
            }
        });

        tfdPaciente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfdPaciente.setText("Anderson Caye");

        try {
            tfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        comboHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o horário", "7:00", "7:30", "8:00", "8:30", "9:00", "9:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", " " }));
        comboHora.setEnabled(false);
        comboHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboHoraActionPerformed(evt);
            }
        });

        btnHora.setText("Buscar horários");
        btnHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfdProfissional, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tfdPlano, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesquisar1, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPesquisar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHora, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(comboHora, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(142, 142, 142))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfdPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfdProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(btnPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfData, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(comboHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHora, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(tfdPlano, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisar2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnPesquisar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/magnifier.png"))); // NOI18N
        btnPesquisar3.setText("Pesquisar");
        btnPesquisar3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPesquisar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisar3ActionPerformed(evt);
            }
        });

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_delete.png"))); // NOI18N
        btnDeletar.setSelected(true);
        btnDeletar.setText("Arquivar");
        btnDeletar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/application_add.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jButton1.setText("Gerar JSON");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_botoesAcaoLayout = new javax.swing.GroupLayout(jp_botoesAcao);
        jp_botoesAcao.setLayout(jp_botoesAcaoLayout);
        jp_botoesAcaoLayout.setHorizontalGroup(
            jp_botoesAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_botoesAcaoLayout.createSequentialGroup()
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPesquisar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jp_botoesAcaoLayout.setVerticalGroup(
            jp_botoesAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_botoesAcaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnPesquisar3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_botoesAcao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_botoesAcao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        Paciente k = (Paciente) Gema.pesquisar(new PacienteDAO());
        
        if (k != null) {
            this.paciente = k;
            preencherPaciente();
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar1ActionPerformed
        Funcionario k = (Funcionario) Gema.pesquisar(new FuncionarioDAO());
        
        if (k != null) {
            this.funcionario = k;
            preencherProfissional();
        }
        

    }//GEN-LAST:event_btnPesquisar1ActionPerformed

    private void tfdPlanoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdPlanoFocusLost
        tfdPlano.setText(this.plano.getNomePlano());
    }//GEN-LAST:event_tfdPlanoFocusLost

    private void btnPesquisar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar2ActionPerformed
        Plano k = (Plano) Gema.pesquisar(new PlanoDAO());
        
        if (k != null) {
            this.plano = k;
            preencherPlano();
        }
    }//GEN-LAST:event_btnPesquisar2ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int resposta = Mensagens.questionarAcao();
        if (resposta == JOptionPane.NO_OPTION) {
            
        } else if (resposta == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnPesquisar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisar3ActionPerformed
        Consultas k = (Consultas) Gema.pesquisar(new ConsultasDAO());
        
        if (k != null) {
            this.consultas = k;
            preencher();
            situacaoVisualizacao();
        }
    }//GEN-LAST:event_btnPesquisar3ActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        int resposta = Mensagens.confirmarArquivamento();
        if (resposta == JOptionPane.YES_OPTION) {
            try {
                String[] infoOld = auditoria();
                String[] infoNew = auditoria();
                Atividade logAuditoria = autoAuditoria(infoOld, infoNew);

                this.consultas.setStatus(false);
                String r;
                r = new ConsultasDAO().update(this.consultas, logAuditoria);
                situacaoNovo();
                if (r == null) {
                    Mensagens.retornoAcao(Mensagens.arquivado("Consultas")); //Acrecentar o resultado da auditoria a msg.
                    limpar();
                    situacaoNovo();
                } else {
                    Mensagens.retornoAcao(Mensagens.erroArquivado("Consultas"));

                }
            } catch (HibernateException he) {
                System.out.println(he);
            }
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        situacaoEditar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            
            int paciente = this.paciente.getIdpaciente();
            int funcionario = this.funcionario.getIdfuncionario();
            String data = tfData.getText();
            String hora = comboHora.getSelectedItem().toString();
            int plano = this.plano.getIdplano();
            
            String[] campos = {"paciente", "profissional", "data", "hora", "plano"};
            String[] valor = {paciente + "", funcionario + "", data, hora, plano + ""};
            Integer[] qtd = {1, 1, 1, 1, 1};
            
            String r = ValidaCampo.campoVazio(campos, qtd, valor);
            
            if (r == null) {
                String[] infoOld = auditoria();
                
                popular();
                
                String[] infoNew = auditoria();
                Atividade logAuditoria = autoAuditoria(infoOld, infoNew);
                
                String s;
                if (consultas.getIdconsultas() != null) {
                    s = new AgendamentoExamesDAO().update(this.consultas, logAuditoria);
                } else {
                    s = new AgendamentoExamesDAO().insert(this.consultas, logAuditoria);
                }
                
                if (s == null) {
                    Mensagens.retornoAcao(Mensagens.salvo("Consulta"));
                    limpar();
                    situacaoNovo();
                } else {
                    Mensagens.retornoAcao(Mensagens.erroSalvar("Consulta"));
                    tfdPaciente.requestFocus();
                }
            } else {
                Mensagens.retornoAcao(Mensagens.preenchaOsCampos("Os seguintes campos obrigatórios estão vazios:\n" + r));
            }
        } catch (HibernateException he) {
            System.out.println(he);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void comboHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboHoraActionPerformed

    }//GEN-LAST:event_comboHoraActionPerformed

    private void btnHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoraActionPerformed
        
        if (!tfData.getText().equals("  /  /    ") && funcionario != null) {
            
            String[] data = tfData.getText().split("/");
            
            int year = Integer.parseInt(data[2]);
            int month = Integer.parseInt(data[1]);
            int day = Integer.parseInt(data[0]);
            
            List<Consultas> k = new ConsultasDAO().selectWithJoin("Consultas", "data_consulta = '" + year + "/" + month + "/" + day + "' and idfuncionario = " + funcionario.getIdfuncionario() + " order by hora_consulta asc");
            
            ArrayList<String> e = new ArrayList();
            
            for (int i = 1; i < comboHora.getItemCount(); i++) {
                for (Consultas j : k) {
                    String s = j.getHoraConsulta().toString().split(":")[0]+":"+j.getHoraConsulta().toString().split(":")[1];
                    if (comboHora.getItemAt(i).equals(s)) {
                        e.add(comboHora.getItemAt(i));
                    }
                }
            }
            
            for (String r : e) {
                comboHora.removeItem(r);
            }
            
            comboHora.setEnabled(true);
        } else {
            Mensagens.retornoAcao(Mensagens.preenchaOsCampos());
        }

    }//GEN-LAST:event_btnHoraActionPerformed

    private void tfdProfissionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfdProfissionalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfdProfissionalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JSON.gerarJSON(this.consultas, Consultas.class);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    @Override
    public void preencher() {
        paciente = consultas.getIdpaciente();
        tfdPaciente.setText(paciente.getIdpessoa().getNomepessoa());
        funcionario = consultas.getIdfuncionario();
        tfdProfissional.setText(funcionario.getIdpessoa().getNomepessoa());
        plano = consultas.getIdplano();
        tfdPlano.setText(plano.getNomePlano());
        
        comboHora.setSelectedItem(consultas.getHoraConsulta().toString().split(":")[0]+":"+consultas.getHoraConsulta().toString().split(":")[1]);
        tfData.setText(Formatacao.ajustaDataDMA(consultas.getDataConsulta().toString()));
        System.out.println(consultas.getDataConsulta().getDay() + "/" + consultas.getDataConsulta().getMonth() + "/" + consultas.getDataConsulta().getYear());
    }
    
    public void preencherPaciente() {
        tfdPaciente.setText(this.paciente.getIdpessoa().getNomepessoa());
    }
    
    public void preencherProfissional() {
        tfdProfissional.setText(this.funcionario.getIdpessoa().getNomepessoa());
    }
    
    public void preencherPlano() {
        tfdPlano.setText(this.plano.getNomePlano());
    }
    
    @Override
    public void limpar() {
        this.consultas = new Consultas();
        this.paciente = new Paciente();
        this.funcionario = new Funcionario();
        this.plano = new Plano();
        
        this.consultas.setIdpaciente(paciente);
        this.consultas.setIdfuncionario(funcionario);
        this.consultas.setIdplano(plano);
        
        tfdPaciente.setText("");
        tfdProfissional.setText("");
        tfdPlano.setText("");
        tfData.setText("");
        comboHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o horário", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "13:00", "13:30", "14:00", "14:30", "15:00", "15:30", "16:00", "16:30", "17:00", "17:30", "18:00", " " }));
        comboHora.setEnabled(false);
    }
    
    @Override
    public void popular() {
        this.consultas.setIdpaciente(paciente);
        this.consultas.setIdfuncionario(funcionario);
        this.consultas.setIdplano(plano);
        this.consultas.setIdformaPagamento(new FormaPagamentoDAO().consultarId(2));
        this.consultas.setIdprontuario(new ProntuarioDAO().consultarId(1));
        this.consultas.setStatus(true);
        
        String[] data = tfData.getText().split("/");
        String hora = comboHora.getSelectedItem()+"";
        
        int year = Integer.parseInt(data[2]);
        int month = Integer.parseInt(data[1]);
        int day = Integer.parseInt(data[0]);
        int hour = Integer.parseInt(hora.split(":")[0]);
        int min = Integer.parseInt(hora.split(":")[1]);
        
        Date dataConsulta = null;
        
        SimpleDateFormat formato = new SimpleDateFormat ("dd/MM/yyyy");
        try {
            dataConsulta = formato.parse(tfData.getText());
        } catch (ParseException ex) {
            Logger.getLogger(AgendamentoExamesJIF.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.consultas.setDataConsulta(dataConsulta);
        this.consultas.setHoraConsulta(new Date(year, month, day, hour, min));
    }
    
    @Override
    public void situacaoNovo() {
        tfdPaciente.setEnabled(false);
        tfdProfissional.setEnabled(false);
        tfData.setEnabled(true);
        comboHora.setEnabled(true);
        tfdPlano.setEnabled(true);
        
        btnCancelar.setEnabled(true);
        btnDeletar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnPesquisar.setEnabled(true);
        btnSalvar.setEnabled(true);
        permissao();
    }
    
    @Override
    public void situacaoEditar() {
        tfdPaciente.setEnabled(true);
        tfdProfissional.setEnabled(true);
        tfData.setEnabled(true);
        comboHora.setEnabled(true);
        tfdPlano.setEnabled(true);
        
        btnCancelar.setEnabled(true);
        btnDeletar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnPesquisar.setEnabled(true);
        btnSalvar.setEnabled(true);
        permissao();
    }
    
    @Override
    public void situacaoVisualizacao() {
        tfdPaciente.setEnabled(false);
        tfdProfissional.setEnabled(false);
        tfData.setEnabled(false);
        comboHora.setEnabled(false);
        tfdPlano.setEnabled(false);
        
        btnCancelar.setEnabled(true);
        btnDeletar.setEnabled(true);
        btnEditar.setEnabled(true);
        btnPesquisar.setEnabled(true);
        btnSalvar.setEnabled(false);
        permissao();
    }
    
    @Override
    public void permissao() {
        btnDeletar.setName("60");
        btnEditar.setName("59");
        btnPesquisar.setName("61");
        btnSalvar.setName("58");
                
        PermissaoG.myCan(can,  jp_botoesAcao.getComponents());
    }


    
    @Override
    public String[] auditoria() {
        String[] r
                = {
                    consultas.getIdconsultas() + "",
                    consultas.getDataConsulta() + "",
                    consultas.getHoraConsulta() + "",
                    consultas.getIdpaciente().getIdpaciente() + "",
                    consultas.getIdfuncionario() + "",
                    consultas.getIdprontuario() + "",
                    consultas.getIdplano() + ""
                
                };
        return r;
    }
    
    @Override
    public Atividade autoAuditoria(String[] iOld, String[] iNew) {
        Atividade logAuditoria = new Atividade();
        logAuditoria.setInformacaoOld(iOld);
        logAuditoria.setInformacaoNew(iNew);
        logAuditoria.setOnde(Atividade.FROM_CONSULTAS);
        logAuditoria.setUsuario(usuario);
        return logAuditoria;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCancelar;
    private javax.swing.JToggleButton btnDeletar;
    private javax.swing.JToggleButton btnEditar;
    private javax.swing.JButton btnHora;
    private javax.swing.JToggleButton btnPesquisar;
    private javax.swing.JToggleButton btnPesquisar1;
    private javax.swing.JToggleButton btnPesquisar2;
    private javax.swing.JToggleButton btnPesquisar3;
    private javax.swing.JToggleButton btnSalvar;
    private javax.swing.JComboBox<String> comboHora;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jp_botoesAcao;
    private javax.swing.JFormattedTextField tfData;
    private javax.swing.JTextField tfdPaciente;
    private javax.swing.JTextField tfdPlano;
    private javax.swing.JTextField tfdProfissional;
    // End of variables declaration//GEN-END:variables
}
