/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import dao.LicenseDAO;
import dao.LoginDAO;
import gema.EncryptDecryptStringWithDES;
import gema.Mensagens;
import gema.VerificaVersion;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.util.logging.Level;
import java.util.logging.Logger;
import negocio.Listapermissao;
import negocio.Usuario;

/**
 *
 * @author anderson.caye
 */
public class LoginJF extends javax.swing.JFrame {

    AvisoInicioSistemaJF a;

    /**
     * Creates new form Login
     */
    public LoginJF() {
        initComponents();
        this.requestFocus();
        VerificaVersion.verificaVersao();
        this.setLocationRelativeTo(null);
//        caregando();
//        new PlanoDAO().select("Plano");
        this.requestFocus();
//        a.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jL_imgUser = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnLogin1 = new javax.swing.JButton();
        jTF_user = new javax.swing.JTextField();
        jPF_pass = new javax.swing.JPasswordField();
        jL_iconUser = new javax.swing.JLabel();
        jL_iconPass = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSenha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login O2 Systems - Porque somos essenciais à vida.");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jL_imgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/imgUser.png"))); // NOI18N

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });

        btnLogin1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnLogin1.setText("Fechar");
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        jTF_user.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTF_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTF_userKeyPressed(evt);
            }
        });

        jPF_pass.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPF_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPF_passKeyPressed(evt);
            }
        });

        jL_iconUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_gray.png"))); // NOI18N

        jL_iconPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/key.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("O2 Systems");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Porque somos essenciais à vida.");

        btnSenha.setBackground(new java.awt.Color(255, 255, 255));
        btnSenha.setText("Esqueceu sua senha?");
        btnSenha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        btnSenha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jL_imgUser)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL_iconUser)
                            .addComponent(jL_iconPass))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_user, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jPF_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jL_imgUser)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTF_user, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_iconUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPF_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_iconPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(btnSenha)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            //Email.sendEmail("elias.flach@universo.univates.br", "Redifinição de Senha", "Teste de redefinição de senha");
            login();
        } catch (IOException ex) {
            Logger.getLogger(LoginJF.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed

        int codigo = evt.getKeyCode();
        int tecla = KeyEvent.VK_ENTER;

        if (codigo == tecla) {
            try {
                this.login();
            } catch (Exception ex) {
                Logger.getLogger(LoginJF.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnLoginKeyPressed

    private void jTF_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTF_userKeyPressed
        int codigo = evt.getKeyCode();
        int tecla = KeyEvent.VK_ENTER;

        if (codigo == tecla) {
            try {
                this.login();
            } catch (Exception ex) {
                Logger.getLogger(LoginJF.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTF_userKeyPressed

    private void jPF_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPF_passKeyPressed
        int codigo = evt.getKeyCode();
        int tecla = KeyEvent.VK_ENTER;

        if (codigo == tecla) {
            try {
                this.login();
            } catch (Exception ex) {
                Logger.getLogger(LoginJF.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jPF_passKeyPressed

    private void btnSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSenhaActionPerformed
        SenhaRecuperarJD a = new SenhaRecuperarJD(new javax.swing.JFrame(), true, jTF_user.getText());
        a.setLocationRelativeTo(null);
        a.setVisible(true);
    }//GEN-LAST:event_btnSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginJF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnSenha;
    private javax.swing.JLabel jL_iconPass;
    private javax.swing.JLabel jL_iconUser;
    private javax.swing.JLabel jL_imgUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPF_pass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTF_user;
    // End of variables declaration//GEN-END:variables

    private void caregando() {
        this.a = new AvisoInicioSistemaJF();
        a.setVisible(true);
    }

    protected static String criptoSenha(String s) throws Exception {
        MessageDigest m = MessageDigest.getInstance("MD5");
        m.update(s.getBytes(), 0, s.length());
        return (new BigInteger(1, m.digest()).toString(16));
    }

    private void login() throws IOException {
        Usuario u = null;
        Listapermissao permissao = null;
        try {
            u = new LoginDAO().acessar(jTF_user.getText(), criptoSenha(jPF_pass.getText()));

        } catch (Exception ex) {
            System.out.println(ex);
        }
        if (u != null) {
            LicenseDAO licenseDAO = new LicenseDAO();
            String key = EncryptDecryptStringWithDES.encrypt(licenseDAO.consultarId(1).getKey());
            String data = EncryptDecryptStringWithDES.encrypt(licenseDAO.consultarId(1).getData());
            
            PrintWriter out = new PrintWriter("/license/license.txt");
            System.out.println("key: "+key);
            System.out.println("data: "+data);
            
            out.println(key);
            out.println(data);
            out.close();
            
                   
            
            PrincipalJF principal = new PrincipalJF(u);
            //PrincipalJF principal = new PrincipalJF((Usuario) new UsuarioDAO().consultarId(1);//  selectWithJoin("Usuario", "nick = 'admin' AND status = true").get(0));
            principal.setVisible(true);
            dispose();
        } else {
            jTF_user.requestFocus();
            Mensagens.retornoAcao("Problemas para realizar o login.\nUsuario ou senha incorretos.");
        }
    }

//    private void pontaPé(){
//        List<Usuario> users = new UsuarioDAO().select("Usuario");
//        List<Listaacao> acoes = new ListaacaoDAO().select("Listaacao");
//        Usuario u = new UsuarioDAO().consultarId(4);
//        ArrayList<String> falhas = new ArrayList();
//        for (Usuario user : users) {
//            Listapermissao lista;
//            for (Listaacao acoe : acoes) {
//                lista = new Listapermissao();
//                lista.setIdusuario(user);
//                lista.setIdlistaacao(acoe);
//                Atividade logAuditoria = new Atividade();
//                String[] o = {"","","",""};
//                String[] n = {lista.getIdlistapermissao()+ "",lista.getIdlistaacao().getIdlistaacao() + "",lista.getIdusuario()+ "","false"};
//                logAuditoria.setInformacaoOld(o);
//                logAuditoria.setInformacaoNew(n);
//                logAuditoria.setOnde(Atividade.FROM_USER_TELA_ACAO);
//                logAuditoria.setUsuario(u);
//                String s = new ListapermissaoDAO().insert(lista, logAuditoria);
//                if(s!=null){
//                    falhas.add("User: " + user.getIdusuario() + " - " + user.getNick()
//                    +"\n"+ acoe.getIdtela().getNomeTela() + " - " + acoe.getIdacaotela().getNomeAcao());
//                }
//            }
//        }
//        if(falhas.size() > 0){
//            for (String falha : falhas) {
//                System.out.println(falha);
//            }
//        }
//    }
}
