/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import com.mballem.app.bean.ChatMessage;
//import com.mballem.app.service.ClienteService;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.net.Socket;
import java.util.Set;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import negocio.Usuario;

/**
 *
 * @author elias
 */
public class PainelAvisosJIF extends javax.swing.JInternalFrame {

    
    Usuario usuario;
    /**
     * Creates new form PainelAvisosJIF
     */
    public PainelAvisosJIF(Usuario usuario) {
        //initComponents();
        this.usuario = usuario;
    }

   //private class ListenerSocket implements Runnable {

        private ObjectInputStream input;

       // public ListenerSocket(Socket socket) {
//            try {
//                this.input = new ObjectInputStream(socket.getInputStream());
//            } catch (IOException ex) {
//                Logger.getLogger(ClienteFrame.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }

//        @Override
//        public void run() {
//            ChatMessage message = null;
//            try {
//                while ((message = (ChatMessage) input.readObject()) != null) {
//                    ChatMessage.Action action = message.getAction();
//
//                    if (action.equals(ChatMessage.Action.CONNECT)) {
//                        connected(message);
//                    } else if (action.equals(ChatMessage.Action.DISCONNECT)) {
//                        disconnected();
//                        socket.close();
//                    } else if (action.equals(ChatMessage.Action.SEND_ONE)) {
//                        System.out.println("::: " + message.getText() + " :::");
//                        receive(message);
//                    } else if (action.equals(ChatMessage.Action.USERS_ONLINE)) {
//                        refreshOnlines(message);
//                    }
//                }
//            } catch (IOException ex) {
//                Logger.getLogger(ChatJIF.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(ChatJIF.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
//    }
//
//    private void connected(ChatMessage message) {
//        if (message.getText().equals("NO")) {
//            JOptionPane.showMessageDialog(this, "Este usuário já está conectado no sistema");
//            btnSair.setEnabled(true);
//            return;
//        } else {
//            this.message = message;
//            this.btnConnectar.setEnabled(false);
//
//            this.btnDesconectar.setEnabled(true);
//            this.txtAreaSend.setEnabled(true);
//            this.txtAreaReceive.setEnabled(true);
//            this.btnEnviar.setEnabled(true);
//            this.btnLimpar.setEnabled(true);
//
//            JOptionPane.showMessageDialog(this, "Você está conectado no chat!");
//        }
//
//    }
//
//    private void disconnected() {
//
//        this.txtAreaReceive.setEnabled(false);
//
//        this.txtAreaReceive.setText("");
//        JOptionPane.showMessageDialog(this, "Você saiu do chat!");
//    }
//
//    private void receive(ChatMessage message) {
//        this.txtAreaReceive.append(message.getName() + " diz: " + message.getText() + "\n");
//    }
//
//    private void refreshOnlines(ChatMessage message) {
//        System.out.println(message.getSetOnlines().toString());
//
//        Set<String> names = message.getSetOnlines();
//
//        names.remove(message.getName());
//
//        String[] array = (String[]) names.toArray(new String[names.size()]);
//
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
//    private void initComponents() {
//
//        jPanel3 = new javax.swing.JPanel();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        txtAreaReceive = new javax.swing.JTextArea();
//        jScrollPane2 = new javax.swing.JScrollPane();
//        txtAreaSend = new javax.swing.JTextArea();
//        btnEnviar = new javax.swing.JButton();
//        btnLimpar = new javax.swing.JButton();
//        jPanel1 = new javax.swing.JPanel();
//        txtName = new javax.swing.JTextField();
//        btnConnectar = new javax.swing.JButton();
//        btnDesconectar = new javax.swing.JButton();
//        jPanel2 = new javax.swing.JPanel();
//        jScrollPane3 = new javax.swing.JScrollPane();
//        listOnlines = new javax.swing.JList();
//        btnSair = new javax.swing.JButton();
//
//        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
//
//        txtAreaReceive.setEditable(false);
//        txtAreaReceive.setColumns(20);
//        txtAreaReceive.setLineWrap(true);
//        txtAreaReceive.setRows(5);
//        txtAreaReceive.setWrapStyleWord(true);
//        txtAreaReceive.setEnabled(false);
//        jScrollPane1.setViewportView(txtAreaReceive);
//
//        txtAreaSend.setColumns(20);
//        txtAreaSend.setLineWrap(true);
//        txtAreaSend.setRows(5);
//        txtAreaSend.setWrapStyleWord(true);
//        txtAreaSend.setEnabled(false);
//        txtAreaSend.addKeyListener(new java.awt.event.KeyAdapter() {
//            public void keyPressed(java.awt.event.KeyEvent evt) {
//                txtAreaSendKeyPressed(evt);
//            }
//        });
//        jScrollPane2.setViewportView(txtAreaSend);
//
//        btnEnviar.setText("Enviar");
//        btnEnviar.setEnabled(false);
//        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnEnviarActionPerformed(evt);
//            }
//        });
//
//        btnLimpar.setText("Limpar");
//        btnLimpar.setEnabled(false);
//        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnLimparActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
//        jPanel3.setLayout(jPanel3Layout);
//        jPanel3Layout.setHorizontalGroup(
//            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel3Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
//                    .addComponent(jScrollPane2)
//                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
//                        .addGap(0, 0, Short.MAX_VALUE)
//                        .addComponent(btnLimpar)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(btnEnviar)))
//                .addContainerGap())
//        );
//        jPanel3Layout.setVerticalGroup(
//            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel3Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(btnEnviar)
//                    .addComponent(btnLimpar))
//                .addContainerGap(22, Short.MAX_VALUE))
//        );
//
//        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Conectar"));
//
//        txtName.setEnabled(false);
//
//        btnConnectar.setText("Conectar");
//        btnConnectar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnConnectarActionPerformed(evt);
//            }
//        });
//
//        btnDesconectar.setText("Desconectar");
//        btnDesconectar.setEnabled(false);
//        btnDesconectar.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnDesconectarActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(txtName)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(btnConnectar)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(btnDesconectar)
//                .addContainerGap())
//        );
//        jPanel1Layout.setVerticalGroup(
//            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addComponent(btnConnectar)
//                .addComponent(btnDesconectar))
//        );
//
//        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Onlines"));
//
//        jScrollPane3.setViewportView(listOnlines);
//
//        btnSair.setText("Sair");
//        btnSair.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                btnSairActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//        jPanel2.setLayout(jPanel2Layout);
//        jPanel2Layout.setHorizontalGroup(
//            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel2Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
//                    .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addContainerGap())
//        );
//        jPanel2Layout.setVerticalGroup(
//            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(jPanel2Layout.createSequentialGroup()
//                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addComponent(btnSair)
//                .addGap(0, 0, Short.MAX_VALUE))
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap())
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(layout.createSequentialGroup()
//                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(layout.createSequentialGroup()
//                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addContainerGap())
//        );
//
//        pack();
//    }// </editor-fold>                        
//
//    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        String text = this.txtAreaSend.getText();
//        String name = this.message.getName();
//
//        this.message = new ChatMessage();
//
//        if (this.listOnlines.getSelectedIndex() > -1) {
//            this.message.setNameReserved((String) this.listOnlines.getSelectedValue());
//            this.message.setAction(ChatMessage.Action.SEND_ONE);
//            this.listOnlines.clearSelection();
//        } else {
//            this.message.setAction(ChatMessage.Action.SEND_ALL);
//        }
//
//        if (!text.isEmpty()) {
//            this.message.setName(name);
//            this.message.setText(text);
//
//            this.txtAreaReceive.append("Você disse: " + text + "\n");
//
//            this.service.send(this.message);
//        }
//
//        this.txtAreaSend.setText("");
//    }                                         
//
//    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {                                          
//        this.txtAreaSend.setText("");
//    }                                         
//
//    private void btnConnectarActionPerformed(java.awt.event.ActionEvent evt) {                                             
//        String name = this.txtName.getText();
//
//        if (!name.isEmpty()) {
//            this.message = new ChatMessage();
//            this.message.setAction(ChatMessage.Action.CONNECT);
//            this.message.setName(name);
//
//            this.service = new ClienteService();
//            this.socket = this.service.connect();
//
//            new Thread(new ListenerSocket(this.socket)).start();
//
//            this.service.send(message);
//            btnSair.setEnabled(false);
//        }
//    }                                            
//
//    private void btnDesconectarActionPerformed(java.awt.event.ActionEvent evt) {                                               
//        ChatMessage message = new ChatMessage();
//        message.setName(this.message.getName());
//        message.setAction(ChatMessage.Action.DISCONNECT);
//        this.service.send(message);
//        disconnected();
//        btnSair.setEnabled(true);
//    }                                              
//
//    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {                                        
//        dispose();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReceive = new javax.swing.JTextArea();

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAreaReceive.setEditable(false);
        txtAreaReceive.setColumns(20);
        txtAreaReceive.setLineWrap(true);
        txtAreaReceive.setRows(5);
        txtAreaReceive.setWrapStyleWord(true);
        txtAreaReceive.setEnabled(false);
        jScrollPane1.setViewportView(txtAreaReceive);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaReceive;
    // End of variables declaration//GEN-END:variables
}