/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import api.PrevisaoTempo;


import controller.PrevisaoTempoController;
import dao.AuditoriaDAO;
import dao.ListapermissaoDAO;
import dao.MensagemRetorno;
import gema.Mensagens;
import gema.VerificaVersion;
import java.io.BufferedInputStream;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;
import negocio.Listapermissao;
import negocio.Usuario;
import org.apache.commons.io.FileUtils;
import static persistencia.PostgresBackup.realizaBackup;
import static persistencia.PostgresRestore.realizaRestore;
import registros.Atividade;
import registros.PermissaoG;

/**
 * 2
 *
 * @author anderson.caye
 */
public class PrincipalJF extends javax.swing.JFrame implements Runnable{

    Usuario usuario;
    List<Listapermissao> permissao;
    TreeMap<Integer, Boolean> can;
    JFileChooser chooser;
    String choosertitle;

    /**
     * Creates new form Principal
     */
    public PrincipalJF(Usuario usuario) throws MalformedURLException, IOException {
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        this.usuario = usuario;
        this.permissao = (List<Listapermissao>) new ListapermissaoDAO().selectWithJoin("Listapermissao", "idusuario = " + this.usuario.getIdusuario() + " order by idlistapermissao asc");
        can = new TreeMap();
        this.montaTree();
        defineNomesComponente();
        permissao();
        
        VerificaVersion();
        
        PainelAvisosJIF k = new PainelAvisosJIF(this.usuario);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() - k.getWidth(), /*this.getHeight() / 2 - k.getHeight() / 2*/ 0);
        k.setVisible(true);

        URL url = new URL("http://meuip.com/api/meuip.php");
        InputStream is = new BufferedInputStream(url.openConnection().getInputStream());
        BufferedReader in = new BufferedReader(new InputStreamReader(is));
        String ip = in.readLine();
        System.out.println(ip);
        this.setTitle("O2 Systems (" + ip + ")");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopRun = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuO2System = new javax.swing.JMenu();
        itemMenuDadosAcesso = new javax.swing.JMenuItem();
        itemMenuGestorUsuario = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        itemMenuAuditoria = new javax.swing.JMenuItem();
        itemMenu_baixarAtualizacao = new javax.swing.JMenuItem();
        itemMenuSobre = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemMenuLogout = new javax.swing.JMenuItem();
        itemMenuSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemMenuFuncionario = new javax.swing.JMenuItem();
        itemMenuPaciente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemMenuEstado = new javax.swing.JMenuItem();
        itemMenuPlano = new javax.swing.JMenuItem();
        itemMenuRemedio = new javax.swing.JMenuItem();
        itemMenuExame = new javax.swing.JMenuItem();
        itemMenuFormaPagamento = new javax.swing.JMenuItem();
        itemMenuFuncao = new javax.swing.JMenuItem();
        menuAgendamento = new javax.swing.JMenu();
        itemMenuConsultasMarcadas = new javax.swing.JMenuItem();
        itemMenuExamesMarcados = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemMenuAgendarConsulta = new javax.swing.JMenuItem();
        itemMenuAgendarExames = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        itemMenuProntuario = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        menuDesenvolvedor = new javax.swing.JMenu();
        itemMenu_CriarPermissao = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        emailAnexo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("O2 Systems");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg_principal.jpg"))); // NOI18N

        jDesktopRun.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopRunLayout = new javax.swing.GroupLayout(jDesktopRun);
        jDesktopRun.setLayout(jDesktopRunLayout);
        jDesktopRunLayout.setHorizontalGroup(
            jDesktopRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jDesktopRunLayout.setVerticalGroup(
            jDesktopRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopRunLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        menuO2System.setText("O2 Systems");
        menuO2System.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuO2SystemActionPerformed(evt);
            }
        });

        itemMenuDadosAcesso.setText("Dados de Acesso");
        menuO2System.add(itemMenuDadosAcesso);

        itemMenuGestorUsuario.setText("Gestor Usuários");
        itemMenuGestorUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuGestorUsuarioActionPerformed(evt);
            }
        });
        menuO2System.add(itemMenuGestorUsuario);
        menuO2System.add(jSeparator5);

        itemMenuAuditoria.setText("Auditoria");
        itemMenuAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAuditoriaActionPerformed(evt);
            }
        });
        menuO2System.add(itemMenuAuditoria);

        itemMenu_baixarAtualizacao.setText("Baixar Atualização");
        menuO2System.add(itemMenu_baixarAtualizacao);

        itemMenuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        itemMenuSobre.setText("Sobre");
        itemMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSobreActionPerformed(evt);
            }
        });
        menuO2System.add(itemMenuSobre);
        menuO2System.add(jSeparator4);

        itemMenuLogout.setText("Logout");
        itemMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuLogoutActionPerformed(evt);
            }
        });
        menuO2System.add(itemMenuLogout);

        itemMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        itemMenuSair.setText("Sair");
        itemMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSairActionPerformed(evt);
            }
        });
        menuO2System.add(itemMenuSair);

        jMenuBar1.add(menuO2System);

        menuCadastro.setText("Cadastro");
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });
        menuCadastro.add(jSeparator2);

        itemMenuFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuFuncionario.setText("Funcionário");
        itemMenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuFuncionario);

        itemMenuPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuPaciente.setText("Paciente");
        itemMenuPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuPacienteActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuPaciente);
        menuCadastro.add(jSeparator1);

        itemMenuEstado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        itemMenuEstado.setText("Estado");
        itemMenuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuEstadoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuEstado);

        itemMenuPlano.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        itemMenuPlano.setText("Plano");
        itemMenuPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuPlanoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuPlano);

        itemMenuRemedio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        itemMenuRemedio.setText("Remédio");
        itemMenuRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRemedioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuRemedio);

        itemMenuExame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        itemMenuExame.setText("Exame");
        itemMenuExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuExameActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuExame);

        itemMenuFormaPagamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        itemMenuFormaPagamento.setText("Forma Pagamento");
        itemMenuFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFormaPagamentoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuFormaPagamento);

        itemMenuFuncao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        itemMenuFuncao.setText("Função");
        itemMenuFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFuncaoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuFuncao);

        jMenuBar1.add(menuCadastro);

        menuAgendamento.setText("Agendamento");
        menuAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgendamentoActionPerformed(evt);
            }
        });

        itemMenuConsultasMarcadas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        itemMenuConsultasMarcadas.setText("Consultas Marcadas");
        itemMenuConsultasMarcadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuConsultasMarcadasActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuConsultasMarcadas);

        itemMenuExamesMarcados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        itemMenuExamesMarcados.setText("Exames Marcados");
        menuAgendamento.add(itemMenuExamesMarcados);
        menuAgendamento.add(jSeparator3);

        itemMenuAgendarConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        itemMenuAgendarConsulta.setText("Agendar Consultas");
        itemMenuAgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAgendarConsultaActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuAgendarConsulta);

        itemMenuAgendarExames.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        itemMenuAgendarExames.setText("Agendar Exames");
        itemMenuAgendarExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAgendarExamesActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuAgendarExames);
        menuAgendamento.add(jSeparator6);

        itemMenuProntuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        itemMenuProntuario.setText("Prontuário");
        itemMenuProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuProntuarioActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuProntuario);

        jMenuBar1.add(menuAgendamento);

        menuRelatorios.setText("Relatórios");
        menuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatoriosActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Dashboard");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menuRelatorios.add(jMenuItem4);

        jMenuBar1.add(menuRelatorios);

        menuDesenvolvedor.setText("Desenvolvedor");
        menuDesenvolvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDesenvolvedorActionPerformed(evt);
            }
        });

        itemMenu_CriarPermissao.setText("Criar Permissão");
        itemMenu_CriarPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenu_CriarPermissaoActionPerformed(evt);
            }
        });
        menuDesenvolvedor.add(itemMenu_CriarPermissao);

        jMenuBar1.add(menuDesenvolvedor);

        jMenu1.setText("Chat");

        jMenuItem2.setText("Chat");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Email");

        emailAnexo.setText("Email com Anexo");
        emailAnexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailAnexoActionPerformed(evt);
            }
        });
        jMenu2.add(emailAnexo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Exportar dados");

        jMenuItem3.setText("XML/JSON");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Importar dados");

        jMenuItem6.setText("JSON");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Temperatura");

        jMenuItem7.setText("Temperatura atual");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Backup/Restauração");

        jMenuItem8.setText("Backup do banco de dados");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenuItem9.setText("Restaurar banco de dados");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem9);

        jMenuItem10.setText("Backup da aplicação");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFuncionarioActionPerformed
        CadastroFuncionarioJIF k = new CadastroFuncionarioJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 0);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuFuncionarioActionPerformed

    private void itemMenuPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuPacienteActionPerformed
        CadastroPacienteJIF k = new CadastroPacienteJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 0);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuPacienteActionPerformed

    private void itemMenuPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuPlanoActionPerformed
        CadastroPlanoSaudeJIF k = new CadastroPlanoSaudeJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuPlanoActionPerformed

    private void itemMenuRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRemedioActionPerformed
        CadastroRemedioJIF k = new CadastroRemedioJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuRemedioActionPerformed

    private void itemMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemMenuSairActionPerformed

    private void itemMenuFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFormaPagamentoActionPerformed
        CadastroFormaPagamentoJIF k = new CadastroFormaPagamentoJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuFormaPagamentoActionPerformed

    private void itemMenuFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFuncaoActionPerformed
        CadastroFuncaoJIF k = new CadastroFuncaoJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuFuncaoActionPerformed

    private void itemMenuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuEstadoActionPerformed
        CadastroEstadoJIF k = new CadastroEstadoJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuEstadoActionPerformed

    private void itemMenuExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuExameActionPerformed
        CadastroExameJIF k = new CadastroExameJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuExameActionPerformed

    private void itemMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSobreActionPerformed
        SobreJIF k = new SobreJIF();
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuSobreActionPerformed

    private void itemMenuAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAuditoriaActionPerformed
        AuditoriaJIF k = new AuditoriaJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuAuditoriaActionPerformed

    private void itemMenuProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuProntuarioActionPerformed
        ProntuarioJIF k = new ProntuarioJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuProntuarioActionPerformed

    private void itemMenuAgendarExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAgendarExamesActionPerformed
        AgendamentoExamesJIF k = new AgendamentoExamesJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuAgendarExamesActionPerformed

    private void itemMenuAgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAgendarConsultaActionPerformed
        AgendamentoConsultaJIF k = new AgendamentoConsultaJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuAgendarConsultaActionPerformed

    private void itemMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuLogoutActionPerformed
        LoginJF login = new LoginJF();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemMenuLogoutActionPerformed

    private void itemMenu_CriarPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenu_CriarPermissaoActionPerformed
        CriacaoPermissaoJIF k = new CriacaoPermissaoJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenu_CriarPermissaoActionPerformed

    private void menuO2SystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuO2SystemActionPerformed
        atualizaPermissao();
    }//GEN-LAST:event_menuO2SystemActionPerformed

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        atualizaPermissao();
    }//GEN-LAST:event_menuCadastroActionPerformed

    private void menuAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgendamentoActionPerformed
        atualizaPermissao();
    }//GEN-LAST:event_menuAgendamentoActionPerformed

    private void menuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatoriosActionPerformed
        atualizaPermissao();
    }//GEN-LAST:event_menuRelatoriosActionPerformed

    private void menuDesenvolvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDesenvolvedorActionPerformed
        atualizaPermissao();
    }//GEN-LAST:event_menuDesenvolvedorActionPerformed

    private void itemMenuGestorUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuGestorUsuarioActionPerformed
        GestorUsuarioJIF k = new GestorUsuarioJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuGestorUsuarioActionPerformed

    private void itemMenuConsultasMarcadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuConsultasMarcadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuConsultasMarcadasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ChatJIF k = new ChatJIF(this.usuario);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
//      
//      ClienteFrame k = new ClienteFrame(this.usuario);
//      k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
//      k.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void emailAnexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailAnexoActionPerformed
        EmailJIF k = new EmailJIF(this.usuario);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_emailAnexoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        ExportarDadosJIF k = new ExportarDadosJIF();
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        JanelaGraficoDashbordJIF k = new JanelaGraficoDashbordJIF();
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ImportarDadosJIF k = new ImportarDadosJIF();
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        try {
            PrevisaoTempoController previsaoController = new PrevisaoTempoController();
            MensagemRetorno msg = previsaoController.consultarAgora();
            if (msg.isSucesso()) {
                PrevisaoTempo p = (PrevisaoTempo) msg.getObjeto();
                String celsius = ((int) p.getTemperatura() + "");
                String previsao = (p.getTempo());
                String previsaoCidade = (p.getCidade());
                String retorno = "Temperatura para " + previsaoCidade + ": " + celsius + " ºC \n ";

                JOptionPane.showMessageDialog(null, retorno);
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao consultar previsão do tempo");
            }
        } catch (IOException ex) {
            Logger.getLogger(PrincipalJF.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        try {
            realizaBackup();
        } catch (IOException ex) {
            Logger.getLogger(PrincipalJF.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(PrincipalJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed

        try {
            String EnderecoAnexo = "";
            File[] Anexo;

            JFileChooser file = new JFileChooser("BACKUP\\");
            file.setMultiSelectionEnabled(true);
            file.setFileSelectionMode(JFileChooser.FILES_ONLY);
            int i = file.showOpenDialog(null);
            if (i == 1) {
                EnderecoAnexo = "";
                Anexo = null;
            } else {
                Anexo = file.getSelectedFiles();
                for (File enderec : Anexo) {
                    EnderecoAnexo = (enderec.getPath());
                    realizaRestore(EnderecoAnexo);

                }
            }
        } catch (IOException ex) {
            Logger.getLogger(PrincipalJF.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "Erro ao restaurar banco de dados: " + ex);
        } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao restaurar banco de dados: " + ex);
            Logger.getLogger(PrincipalJF.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        JOptionPane.showMessageDialog(null, "Especifique o diretório do projeto!");
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle(choosertitle);
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //    
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            System.out.println("getCurrentDirectory(): "
                    + chooser.getCurrentDirectory());
            System.out.println("getSelectedFile() : "
                    + chooser.getSelectedFile());
        } else {
            System.out.println("No Selection ");
        }

    String source = chooser.getCurrentDirectory().toString();
    File srcDir = new File(source);

    String destination = "C:/";
    File destDir = new File(destination);

    
        try {
    FileUtils.copyDirectory(srcDir, destDir);
    JOptionPane.showMessageDialog(null, "Backup relizado com sucesso para "+destDir);
    }
    catch (IOException e) {
    e.printStackTrace();
    JOptionPane.showMessageDialog(null, "Erro ao realizar backup do projeto: "+e);}


    }//GEN-LAST:event_jMenuItem10ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PrincipalJF().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem emailAnexo;
    private javax.swing.JMenuItem itemMenuAgendarConsulta;
    private javax.swing.JMenuItem itemMenuAgendarExames;
    private javax.swing.JMenuItem itemMenuAuditoria;
    private javax.swing.JMenuItem itemMenuConsultasMarcadas;
    private javax.swing.JMenuItem itemMenuDadosAcesso;
    private javax.swing.JMenuItem itemMenuEstado;
    private javax.swing.JMenuItem itemMenuExame;
    private javax.swing.JMenuItem itemMenuExamesMarcados;
    private javax.swing.JMenuItem itemMenuFormaPagamento;
    private javax.swing.JMenuItem itemMenuFuncao;
    private javax.swing.JMenuItem itemMenuFuncionario;
    private javax.swing.JMenuItem itemMenuGestorUsuario;
    private javax.swing.JMenuItem itemMenuLogout;
    private javax.swing.JMenuItem itemMenuPaciente;
    private javax.swing.JMenuItem itemMenuPlano;
    private javax.swing.JMenuItem itemMenuProntuario;
    private javax.swing.JMenuItem itemMenuRemedio;
    private javax.swing.JMenuItem itemMenuSair;
    private javax.swing.JMenuItem itemMenuSobre;
    private javax.swing.JMenuItem itemMenu_CriarPermissao;
    private javax.swing.JMenuItem itemMenu_baixarAtualizacao;
    private javax.swing.JDesktopPane jDesktopRun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenu menuAgendamento;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuDesenvolvedor;
    private javax.swing.JMenu menuO2System;
    private javax.swing.JMenu menuRelatorios;
    // End of variables declaration//GEN-END:variables

    private void permissao() {
        menuDesenvolvedor.setVisible(PermissaoG.canUse(menuDesenvolvedor.isEnabled(), can.get(1)));

        itemMenuAuditoria.setName("13");
        PermissaoG.myCan(can, menuO2System.getMenuComponents());
        PermissaoG.myCan(can, menuAgendamento.getMenuComponents());
        PermissaoG.myCan(can, menuCadastro.getMenuComponents());
        PermissaoG.myCan(can, menuDesenvolvedor.getMenuComponents());
        PermissaoG.myCan(can, menuRelatorios.getMenuComponents());
    }

    private void defineNomesComponente() {
        itemMenuAuditoria.setName("13");
        itemMenuSobre.setName("89");
        itemMenuAgendarConsulta.setName("57");
        itemMenuAgendarExames.setName("62");
        itemMenuDadosAcesso.setName("78");
        itemMenuExame.setName("42");
        itemMenuConsultasMarcadas.setName("97");
        itemMenuExamesMarcados.setName("96");
        itemMenuFormaPagamento.setName("47");
        itemMenuFuncionario.setName("17");
        itemMenuPaciente.setName("22");
        itemMenuPlano.setName("32");
        itemMenuProntuario.setName("67");
        itemMenuRemedio.setName("37");
        itemMenuGestorUsuario.setName("84");
        itemMenuEstado.setName("27");
        itemMenuFuncao.setName("52");
        itemMenu_CriarPermissao.setName("1");
    }

    private void montaTree() {
        for (Listapermissao use : permissao) {
            this.can.put(use.getIdlistaacao().getIdlistaacao(), use.getPermissao());
        }
    }

    private void atualizaPermissao() {
        permissao();
    }
    
    /* Verificação de Atualização */
    public void movimentoAtualizacaoVersion(boolean isAtualizada){
        if(isAtualizada){
            itemMenu_baixarAtualizacao.setVisible(false);
            menuO2System.setText("O2 Systems");
        } else {
            itemMenu_baixarAtualizacao.setVisible(true);
            menuO2System.setText("O2 Systems - SISTEMA DESATUALIZADO");
        }
    }
    
    public void VerificaVersion() {
        Thread t = new Thread(this);
        t.start();
    }
    
    @Override
    public void run(){
        int i = 0;
        boolean b = !VerificaVersion.runVersion();
        while(true){
            try {
                boolean temp = b;
                b = !VerificaVersion.runVersion();
                if(temp != b){ i = 0;}
                System.out.println("testes = " + (i) + "  de execução - " + b);
                movimentoAtualizacaoVersion( b );
                avisadoCliente(i, b);
                Thread.sleep(30000);
                i++;
            } catch (InterruptedException ex) {
                Logger.getLogger(PrincipalJF.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void avisadoCliente(int i, boolean b) {
        String n = "desatualizado";
        if(b){ n = "atualizado";}
        if(i == 0){
            Atividade logAuditoria = new Atividade();
            String[] s = {"Cliente notificado que o sistema está "+n};
            logAuditoria.setInformacaoOld(s);
            logAuditoria.setInformacaoNew(s);
            logAuditoria.setOnde(Atividade.FROM_VERIFICA_VERSION);
            logAuditoria.setUsuario(usuario);
            
            new AuditoriaDAO().insertAuditoria(logAuditoria.registraAtividade());
        
        }
    }
}
