/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import dao.ListapermissaoDAO;
import dao.UsuarioDAO;
import java.util.List;
import java.util.TreeMap;
import negocio.Listapermissao;
import negocio.Usuario;
import registros.PermissaoG;

/**
 * 2
 *
 * @author anderson.caye
 */
public class PrincipalJF extends javax.swing.JFrame {

    Usuario usuario;
    List<Listapermissao> permissao;
    TreeMap<Integer, Boolean> can;

    /**
     * Creates new form Principal
     */
    public PrincipalJF(Usuario usuario) {
        this.setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        this.usuario = usuario;
        this.permissao = (List<Listapermissao>) new ListapermissaoDAO().selectWithJoin("Listapermissao", "idusuario = " + this.usuario.getIdusuario() + " order by idlistapermissao asc");
        can = new TreeMap();
        this.montaTree();
        defineNomesComponente();
        permissao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopRun = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuO2System = new javax.swing.JMenu();
        itemMenuDadosAcesso = new javax.swing.JMenuItem();
        itemMenuGestorUsuario = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        itemMenuAuditoria = new javax.swing.JMenuItem();
        itemMenuSobre = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemMenuLogout = new javax.swing.JMenuItem();
        itemMenuSair = new javax.swing.JMenuItem();
        menuCadastro = new javax.swing.JMenu();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemMenuFuncionario = new javax.swing.JMenuItem();
        itemMenuPaciente = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemMenuEstado = new javax.swing.JMenuItem();
        itemMenuPlano = new javax.swing.JMenuItem();
        itemMenuRemedio = new javax.swing.JMenuItem();
        itemMenuExame = new javax.swing.JMenuItem();
        itemMenuFormaPagamento = new javax.swing.JMenuItem();
        itemMenuFuncao = new javax.swing.JMenuItem();
        menuAgendamento = new javax.swing.JMenu();
        itemMenuConsultasMarcadas = new javax.swing.JMenuItem();
        itemMenuExamesMarcados = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        itemMenuAgendarConsulta = new javax.swing.JMenuItem();
        itemMenuAgendarExames = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        itemMenuProntuario = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuDesenvolvedor = new javax.swing.JMenu();
        itemMenu_CriarPermissao = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("O2 Systems");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/bg_principal.jpg"))); // NOI18N

        jDesktopRun.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopRunLayout = new javax.swing.GroupLayout(jDesktopRun);
        jDesktopRun.setLayout(jDesktopRunLayout);
        jDesktopRunLayout.setHorizontalGroup(
            jDesktopRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jDesktopRunLayout.setVerticalGroup(
            jDesktopRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopRunLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        menuO2System.setText("O2 Systems");
        menuO2System.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuO2SystemActionPerformed(evt);
            }
        });

        itemMenuDadosAcesso.setText("Dados de Acesso");
        menuO2System.add(itemMenuDadosAcesso);

        itemMenuGestorUsuario.setText("Gestor Usuários");
        itemMenuGestorUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuGestorUsuarioActionPerformed(evt);
            }
        });
        menuO2System.add(itemMenuGestorUsuario);
        menuO2System.add(jSeparator5);

        itemMenuAuditoria.setText("Auditoria");
        itemMenuAuditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAuditoriaActionPerformed(evt);
            }
        });
        menuO2System.add(itemMenuAuditoria);

        itemMenuSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F11, 0));
        itemMenuSobre.setText("Sobre");
        itemMenuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSobreActionPerformed(evt);
            }
        });
        menuO2System.add(itemMenuSobre);
        menuO2System.add(jSeparator4);

        itemMenuLogout.setText("Logout");
        itemMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuLogoutActionPerformed(evt);
            }
        });
        menuO2System.add(itemMenuLogout);

        itemMenuSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, 0));
        itemMenuSair.setText("Sair");
        itemMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuSairActionPerformed(evt);
            }
        });
        menuO2System.add(itemMenuSair);

        jMenuBar1.add(menuO2System);

        menuCadastro.setText("Cadastro");
        menuCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastroActionPerformed(evt);
            }
        });
        menuCadastro.add(jSeparator2);

        itemMenuFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuFuncionario.setText("Funcionário");
        itemMenuFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFuncionarioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuFuncionario);

        itemMenuPaciente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        itemMenuPaciente.setText("Paciente");
        itemMenuPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuPacienteActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuPaciente);
        menuCadastro.add(jSeparator1);

        itemMenuEstado.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        itemMenuEstado.setText("Estado");
        itemMenuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuEstadoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuEstado);

        itemMenuPlano.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        itemMenuPlano.setText("Plano");
        itemMenuPlano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuPlanoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuPlano);

        itemMenuRemedio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        itemMenuRemedio.setText("Remédio");
        itemMenuRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRemedioActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuRemedio);

        itemMenuExame.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        itemMenuExame.setText("Exame");
        itemMenuExame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuExameActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuExame);

        itemMenuFormaPagamento.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        itemMenuFormaPagamento.setText("Forma Pagamento");
        itemMenuFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFormaPagamentoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuFormaPagamento);

        itemMenuFuncao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        itemMenuFuncao.setText("Função");
        itemMenuFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuFuncaoActionPerformed(evt);
            }
        });
        menuCadastro.add(itemMenuFuncao);

        jMenuBar1.add(menuCadastro);

        menuAgendamento.setText("Agendamento");
        menuAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAgendamentoActionPerformed(evt);
            }
        });

        itemMenuConsultasMarcadas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        itemMenuConsultasMarcadas.setText("Consultas Marcadas");
        itemMenuConsultasMarcadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuConsultasMarcadasActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuConsultasMarcadas);

        itemMenuExamesMarcados.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        itemMenuExamesMarcados.setText("Exames Marcados");
        menuAgendamento.add(itemMenuExamesMarcados);
        menuAgendamento.add(jSeparator3);

        itemMenuAgendarConsulta.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        itemMenuAgendarConsulta.setText("Agendar Consultas");
        itemMenuAgendarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAgendarConsultaActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuAgendarConsulta);

        itemMenuAgendarExames.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        itemMenuAgendarExames.setText("Agendar Exames");
        itemMenuAgendarExames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuAgendarExamesActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuAgendarExames);
        menuAgendamento.add(jSeparator6);

        itemMenuProntuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        itemMenuProntuario.setText("Prontuário");
        itemMenuProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuProntuarioActionPerformed(evt);
            }
        });
        menuAgendamento.add(itemMenuProntuario);

        jMenuBar1.add(menuAgendamento);

        menuRelatorios.setText("Relatórios");
        menuRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelatoriosActionPerformed(evt);
            }
        });
        jMenuBar1.add(menuRelatorios);

        menuDesenvolvedor.setText("Desenvolvedor");
        menuDesenvolvedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDesenvolvedorActionPerformed(evt);
            }
        });

        itemMenu_CriarPermissao.setText("Criar Permissão");
        itemMenu_CriarPermissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenu_CriarPermissaoActionPerformed(evt);
            }
        });
        menuDesenvolvedor.add(itemMenu_CriarPermissao);

        jMenuBar1.add(menuDesenvolvedor);

        jMenu1.setText("Chat");

        jMenuItem2.setText("Chat");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMenuFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFuncionarioActionPerformed
        CadastroFuncionarioJIF k = new CadastroFuncionarioJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 0);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuFuncionarioActionPerformed

    private void itemMenuPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuPacienteActionPerformed
        CadastroPacienteJIF k = new CadastroPacienteJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 0);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuPacienteActionPerformed

    private void itemMenuPlanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuPlanoActionPerformed
        CadastroPlanoSaudeJIF k = new CadastroPlanoSaudeJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuPlanoActionPerformed

    private void itemMenuRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRemedioActionPerformed
        CadastroRemedioJIF k = new CadastroRemedioJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuRemedioActionPerformed

    private void itemMenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemMenuSairActionPerformed

    private void itemMenuFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFormaPagamentoActionPerformed
        CadastroFormaPagamentoJIF k = new CadastroFormaPagamentoJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuFormaPagamentoActionPerformed

    private void itemMenuFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuFuncaoActionPerformed
        CadastroFuncaoJIF k = new CadastroFuncaoJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuFuncaoActionPerformed

    private void itemMenuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuEstadoActionPerformed
        CadastroEstadoJIF k = new CadastroEstadoJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuEstadoActionPerformed

    private void itemMenuExameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuExameActionPerformed
        CadastroExameJIF k = new CadastroExameJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuExameActionPerformed

    private void itemMenuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuSobreActionPerformed
        SobreJIF k = new SobreJIF();
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuSobreActionPerformed

    private void itemMenuAuditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAuditoriaActionPerformed
        AuditoriaJIF k = new AuditoriaJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuAuditoriaActionPerformed

    private void itemMenuProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuProntuarioActionPerformed
        ProntuarioJIF k = new ProntuarioJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuProntuarioActionPerformed

    private void itemMenuAgendarExamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAgendarExamesActionPerformed
        AgendamentoExamesJIF k = new AgendamentoExamesJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuAgendarExamesActionPerformed

    private void itemMenuAgendarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuAgendarConsultaActionPerformed
        AgendamentoConsultaJIF k = new AgendamentoConsultaJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuAgendarConsultaActionPerformed

    private void itemMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuLogoutActionPerformed
        LoginJF login = new LoginJF();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_itemMenuLogoutActionPerformed

    private void itemMenu_CriarPermissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenu_CriarPermissaoActionPerformed
        CriacaoPermissaoJIF k = new CriacaoPermissaoJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenu_CriarPermissaoActionPerformed

    private void menuO2SystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuO2SystemActionPerformed
        atualizaPermissao();
    }//GEN-LAST:event_menuO2SystemActionPerformed

    private void menuCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastroActionPerformed
        atualizaPermissao();
    }//GEN-LAST:event_menuCadastroActionPerformed

    private void menuAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAgendamentoActionPerformed
        atualizaPermissao();
    }//GEN-LAST:event_menuAgendamentoActionPerformed

    private void menuRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelatoriosActionPerformed
        atualizaPermissao();
    }//GEN-LAST:event_menuRelatoriosActionPerformed

    private void menuDesenvolvedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDesenvolvedorActionPerformed
        atualizaPermissao();
    }//GEN-LAST:event_menuDesenvolvedorActionPerformed

    private void itemMenuGestorUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuGestorUsuarioActionPerformed
        GestorUsuarioJIF k = new GestorUsuarioJIF(this.usuario, this.can);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
    }//GEN-LAST:event_itemMenuGestorUsuarioActionPerformed

    private void itemMenuConsultasMarcadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuConsultasMarcadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMenuConsultasMarcadasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ChatJIF k = new ChatJIF(this.usuario);
        jDesktopRun.add(k);
        k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
        k.setVisible(true);
//      
//      ClienteFrame k = new ClienteFrame(this.usuario);
//      k.setLocation(this.getWidth() / 2 - k.getWidth() / 2, /*this.getHeight() / 2 - k.getHeight() / 2*/ 10);
//      k.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(PrincipalJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new PrincipalJF().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemMenuAgendarConsulta;
    private javax.swing.JMenuItem itemMenuAgendarExames;
    private javax.swing.JMenuItem itemMenuAuditoria;
    private javax.swing.JMenuItem itemMenuConsultasMarcadas;
    private javax.swing.JMenuItem itemMenuDadosAcesso;
    private javax.swing.JMenuItem itemMenuEstado;
    private javax.swing.JMenuItem itemMenuExame;
    private javax.swing.JMenuItem itemMenuExamesMarcados;
    private javax.swing.JMenuItem itemMenuFormaPagamento;
    private javax.swing.JMenuItem itemMenuFuncao;
    private javax.swing.JMenuItem itemMenuFuncionario;
    private javax.swing.JMenuItem itemMenuGestorUsuario;
    private javax.swing.JMenuItem itemMenuLogout;
    private javax.swing.JMenuItem itemMenuPaciente;
    private javax.swing.JMenuItem itemMenuPlano;
    private javax.swing.JMenuItem itemMenuProntuario;
    private javax.swing.JMenuItem itemMenuRemedio;
    private javax.swing.JMenuItem itemMenuSair;
    private javax.swing.JMenuItem itemMenuSobre;
    private javax.swing.JMenuItem itemMenu_CriarPermissao;
    private javax.swing.JDesktopPane jDesktopRun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenu menuAgendamento;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuDesenvolvedor;
    private javax.swing.JMenu menuO2System;
    private javax.swing.JMenu menuRelatorios;
    // End of variables declaration//GEN-END:variables

    private void permissao() {
        menuDesenvolvedor.setVisible(PermissaoG.canUse(menuDesenvolvedor.isEnabled(), can.get(1)));

        itemMenuAuditoria.setName("13");
        PermissaoG.myCan(can, menuO2System.getMenuComponents());
        PermissaoG.myCan(can, menuAgendamento.getMenuComponents());
        PermissaoG.myCan(can, menuCadastro.getMenuComponents());
        PermissaoG.myCan(can, menuDesenvolvedor.getMenuComponents());
        PermissaoG.myCan(can, menuRelatorios.getMenuComponents());
    }

    private void defineNomesComponente() {
        itemMenuAuditoria.setName("13");
        itemMenuSobre.setName("89");
        itemMenuAgendarConsulta.setName("57");
        itemMenuAgendarExames.setName("62");
        itemMenuDadosAcesso.setName("78");
        itemMenuExame.setName("42");
        itemMenuConsultasMarcadas.setName("97");
        itemMenuExamesMarcados.setName("96");
        itemMenuFormaPagamento.setName("47");
        itemMenuFuncionario.setName("17");
        itemMenuPaciente.setName("22");
        itemMenuPlano.setName("32");
        itemMenuProntuario.setName("67");
        itemMenuRemedio.setName("37");
        itemMenuGestorUsuario.setName("84");
        itemMenuEstado.setName("27");
        itemMenuFuncao.setName("52");
        itemMenu_CriarPermissao.setName("1");
    }

    private void montaTree() {
        for (Listapermissao use : permissao) {
            this.can.put(use.getIdlistaacao().getIdlistaacao(), use.getPermissao());
        }
    }

    private void atualizaPermissao() {
        permissao();
    }
}
