package negocio;
// Generated 08/08/2018 19:55:37 by Hibernate Tools 4.3.1



/**
 * ListagemPlanos generated by hbm2java
 */
public class ListagemPlanos  implements java.io.Serializable {


     private int idlistagemPlano;
     private Paciente paciente;
     private Plano plano;
     private String codigoPlano;

    public ListagemPlanos() {
    }

    public ListagemPlanos(int idlistagemPlano, Paciente paciente, Plano plano, String codigoPlano) {
       this.idlistagemPlano = idlistagemPlano;
       this.paciente = paciente;
       this.plano = plano;
       this.codigoPlano = codigoPlano;
    }
   
    public int getIdlistagemPlano() {
        return this.idlistagemPlano;
    }
    
    public void setIdlistagemPlano(int idlistagemPlano) {
        this.idlistagemPlano = idlistagemPlano;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Plano getPlano() {
        return this.plano;
    }
    
    public void setPlano(Plano plano) {
        this.plano = plano;
    }
    public String getCodigoPlano() {
        return this.codigoPlano;
    }
    
    public void setCodigoPlano(String codigoPlano) {
        this.codigoPlano = codigoPlano;
    }




}


