package negocio;
// Generated 08/08/2018 19:55:37 by Hibernate Tools 4.3.1



/**
 * ListagemExames generated by hbm2java
 */
public class ListagemExames  implements java.io.Serializable {


     private int idlistagemExames;
     private Exames exames;
     private Requisicao requisicao;
     private String observacao;

    public ListagemExames() {
    }

    public ListagemExames(int idlistagemExames, Exames exames, Requisicao requisicao, String observacao) {
       this.idlistagemExames = idlistagemExames;
       this.exames = exames;
       this.requisicao = requisicao;
       this.observacao = observacao;
    }
   
    public int getIdlistagemExames() {
        return this.idlistagemExames;
    }
    
    public void setIdlistagemExames(int idlistagemExames) {
        this.idlistagemExames = idlistagemExames;
    }
    public Exames getExames() {
        return this.exames;
    }
    
    public void setExames(Exames exames) {
        this.exames = exames;
    }
    public Requisicao getRequisicao() {
        return this.requisicao;
    }
    
    public void setRequisicao(Requisicao requisicao) {
        this.requisicao = requisicao;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }




}


