package negocio;
// Generated 08/08/2018 19:55:37 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private int idpessoa;
     private Cidade cidade;
     private String nomePessoa;
     private String sobrenome;
     private String cpf;
     private String rg;
     private String sexo;
     private Date dataNascimento;
     private String logradouro;
     private String complemento;
     private String cep;
     private Boolean status;
     private Set<Funcionario> funcionarios = new HashSet<Funcionario>(0);
     private Set<Paciente> pacientes = new HashSet<Paciente>(0);

    public Pessoa() {
    }

	
    public Pessoa(int idpessoa, Cidade cidade, String nomePessoa, String sobrenome, String rg, String sexo, Date dataNascimento, String logradouro) {
        this.idpessoa = idpessoa;
        this.cidade = cidade;
        this.nomePessoa = nomePessoa;
        this.sobrenome = sobrenome;
        this.rg = rg;
        this.sexo = sexo;
        this.dataNascimento = dataNascimento;
        this.logradouro = logradouro;
    }
    public Pessoa(int idpessoa, Cidade cidade, String nomePessoa, String sobrenome, String cpf, String rg, String sexo, Date dataNascimento, String logradouro, String complemento, String cep, Boolean status, Set<Funcionario> funcionarios, Set<Paciente> pacientes) {
       this.idpessoa = idpessoa;
       this.cidade = cidade;
       this.nomePessoa = nomePessoa;
       this.sobrenome = sobrenome;
       this.cpf = cpf;
       this.rg = rg;
       this.sexo = sexo;
       this.dataNascimento = dataNascimento;
       this.logradouro = logradouro;
       this.complemento = complemento;
       this.cep = cep;
       this.status = status;
       this.funcionarios = funcionarios;
       this.pacientes = pacientes;
    }
   
    public int getIdpessoa() {
        return this.idpessoa;
    }
    
    public void setIdpessoa(int idpessoa) {
        this.idpessoa = idpessoa;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public String getNomePessoa() {
        return this.nomePessoa;
    }
    
    public void setNomePessoa(String nomePessoa) {
        this.nomePessoa = nomePessoa;
    }
    public String getSobrenome() {
        return this.sobrenome;
    }
    
    public void setSobrenome(String sobrenome) {
        this.sobrenome = sobrenome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Set<Funcionario> getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set<Funcionario> funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set<Paciente> getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set<Paciente> pacientes) {
        this.pacientes = pacientes;
    }




}


