package negocio;
// Generated 08/08/2018 19:55:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Plano generated by hbm2java
 */
public class Plano  implements java.io.Serializable {


     private int idplano;
     private String nomePlano;
     private Set<AgendamentoExames> agendamentoExameses = new HashSet<AgendamentoExames>(0);
     private Set<Consultas> consultases = new HashSet<Consultas>(0);
     private Set<ListagemPlanos> listagemPlanoses = new HashSet<ListagemPlanos>(0);

    public Plano() {
    }

	
    public Plano(int idplano, String nomePlano) {
        this.idplano = idplano;
        this.nomePlano = nomePlano;
    }
    public Plano(int idplano, String nomePlano, Set<AgendamentoExames> agendamentoExameses, Set<Consultas> consultases, Set<ListagemPlanos> listagemPlanoses) {
       this.idplano = idplano;
       this.nomePlano = nomePlano;
       this.agendamentoExameses = agendamentoExameses;
       this.consultases = consultases;
       this.listagemPlanoses = listagemPlanoses;
    }
   
    public int getIdplano() {
        return this.idplano;
    }
    
    public void setIdplano(int idplano) {
        this.idplano = idplano;
    }
    public String getNomePlano() {
        return this.nomePlano;
    }
    
    public void setNomePlano(String nomePlano) {
        this.nomePlano = nomePlano;
    }
    public Set<AgendamentoExames> getAgendamentoExameses() {
        return this.agendamentoExameses;
    }
    
    public void setAgendamentoExameses(Set<AgendamentoExames> agendamentoExameses) {
        this.agendamentoExameses = agendamentoExameses;
    }
    public Set<Consultas> getConsultases() {
        return this.consultases;
    }
    
    public void setConsultases(Set<Consultas> consultases) {
        this.consultases = consultases;
    }
    public Set<ListagemPlanos> getListagemPlanoses() {
        return this.listagemPlanoses;
    }
    
    public void setListagemPlanoses(Set<ListagemPlanos> listagemPlanoses) {
        this.listagemPlanoses = listagemPlanoses;
    }




}


