package negocio;
// Generated 08/08/2018 19:55:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Prontuario generated by hbm2java
 */
public class Prontuario  implements java.io.Serializable {


     private int idprontuario;
     private Receita receita;
     private Requisicao requisicao;
     private String triagem;
     private String atendimento;
     private Set<Consultas> consultases = new HashSet<Consultas>(0);

    public Prontuario() {
    }

	
    public Prontuario(int idprontuario, Receita receita, Requisicao requisicao, String triagem, String atendimento) {
        this.idprontuario = idprontuario;
        this.receita = receita;
        this.requisicao = requisicao;
        this.triagem = triagem;
        this.atendimento = atendimento;
    }
    public Prontuario(int idprontuario, Receita receita, Requisicao requisicao, String triagem, String atendimento, Set<Consultas> consultases) {
       this.idprontuario = idprontuario;
       this.receita = receita;
       this.requisicao = requisicao;
       this.triagem = triagem;
       this.atendimento = atendimento;
       this.consultases = consultases;
    }
   
    public int getIdprontuario() {
        return this.idprontuario;
    }
    
    public void setIdprontuario(int idprontuario) {
        this.idprontuario = idprontuario;
    }
    public Receita getReceita() {
        return this.receita;
    }
    
    public void setReceita(Receita receita) {
        this.receita = receita;
    }
    public Requisicao getRequisicao() {
        return this.requisicao;
    }
    
    public void setRequisicao(Requisicao requisicao) {
        this.requisicao = requisicao;
    }
    public String getTriagem() {
        return this.triagem;
    }
    
    public void setTriagem(String triagem) {
        this.triagem = triagem;
    }
    public String getAtendimento() {
        return this.atendimento;
    }
    
    public void setAtendimento(String atendimento) {
        this.atendimento = atendimento;
    }
    public Set<Consultas> getConsultases() {
        return this.consultases;
    }
    
    public void setConsultases(Set<Consultas> consultases) {
        this.consultases = consultases;
    }




}


